### PR TITLE
feat: add all games button

### PR DESCRIPTION
**Pull request by jssotomdz**
This is how the button looks right now
2024-01-19-11_49_20-screenshot(1)

### CODE REVIEW

**Comment by jssotomdz** [comment]
> I think it's fine, but maybe it could be more prominent?
From the `yaru.dart` https://github.com/ubuntu/yaru.dart
Light green or dark green? Because the orange one is way less prominent

**Comment by ashuntu** [comment]
> > I think it's fine, but maybe it could be more prominent?
> 
> From the `yaru.dart` https://github.com/ubuntu/yaru.dart Light green or dark green? Because the orange one is way less prominent

Probably dark?

**Comment by jssotomdz** [comment]
Visually looks good but I'm concerned about that green (yours is probably blue) since it is used for updates or install buttons so maybe it is only meant for important stuff. 
2024-01-19-12_08_13-screenshot(1)

**Comment by ashuntu** [comment]
Maybe make the container the button is in have more padding so its clearly distinct from the rest. You could also make the button full width, but I'm not sure if that will look good or not

**Comment by jssotomdz** [comment]
well this is def ui/designer stuff. The functionality is there and we can ping design later to decide about these specifics

**Pull request merged**
